[2021-09-20 14:31:01,330] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: branching-dag.Conditional_Select 2020-07-25T00:00:00+00:00 [queued]>
[2021-09-20 14:31:01,338] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: branching-dag.Conditional_Select 2020-07-25T00:00:00+00:00 [queued]>
[2021-09-20 14:31:01,339] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-09-20 14:31:01,340] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-09-20 14:31:01,340] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-09-20 14:31:01,352] {taskinstance.py:1114} INFO - Executing <Task(BranchPythonOperator): Conditional_Select> on 2020-07-25T00:00:00+00:00
[2021-09-20 14:31:01,356] {standard_task_runner.py:52} INFO - Started process 817 to run task
[2021-09-20 14:31:01,360] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'branching-dag', 'Conditional_Select', '2020-07-25T00:00:00+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/xcom_branching.py', '--cfg-path', '/tmp/tmppl26xd9v', '--error-file', '/tmp/tmp89w0lbwz']
[2021-09-20 14:31:01,361] {standard_task_runner.py:77} INFO - Job 7: Subtask Conditional_Select
[2021-09-20 14:31:01,402] {logging_mixin.py:109} INFO - Running <TaskInstance: branching-dag.Conditional_Select 2020-07-25T00:00:00+00:00 [running]> on host ba08e7b1fb26
[2021-09-20 14:31:01,447] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=myemail@mail.com
AIRFLOW_CTX_DAG_OWNER=rab4u
AIRFLOW_CTX_DAG_ID=branching-dag
AIRFLOW_CTX_TASK_ID=Conditional_Select
AIRFLOW_CTX_EXECUTION_DATE=2020-07-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-07-25T00:00:00+00:00
[2021-09-20 14:31:01,456] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 179, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/xcom_branching.py", line 33, in condition
    if result > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
[2021-09-20 14:31:01,460] {taskinstance.py:1505} INFO - Marking task as UP_FOR_RETRY. dag_id=branching-dag, task_id=Conditional_Select, execution_date=20200725T000000, start_date=20210920T143101, end_date=20210920T143101
[2021-09-20 14:31:01,493] {local_task_job.py:151} INFO - Task exited with return code 1
[2021-09-20 14:31:01,517] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
